### ISSUE TITLE
Todo 2017

### ISSUE THREAD

**Issue by redhog** [piratpartiet/skutan#1]
- [x] Inköpsrunda
  - [x] Trä
  - [x] Linolja
  - [x] Terpentin
  - [x] Motorolja
  - [x] Korkbollar
- [x] Köra segel/presenning/madrasser
- [x] Byta olja i motorn
- [x] Olja master
- [x] Olja däck
- [x] Fendertrep
- [x] Livbojshållare 90x14 + 45x14
- [x] Lantärnehus 18x20x3
- [x] Kylskåp - skaffa plåt att lägga ovanpå
- [ ] Ta bort ruttet trä poch ersätt med plast
- [ ] Skotknap
- [ ] Hyllor Höjd 110, Djup 100, bredd 50
- [x] Vägg prälspont - i fören 48x140 + 70x140
- [ ] Hantag på durk
- [x] Plugg
- [x] Flytta båtdjäveln - torsdag
- [x] Nåta däck
- [x] Ta av presenning
* What to fix while being out
  * [x] Extra bildge pump (temporarily?)
  * [x] Oil things that we didn't oil before this year.
  * [ ] Fix oar holder on dingy

**Comment by redhog** [comment]
Köp: nytt block (1 hjul), slang för länspump, motorolja,

**Comment by Gontesque** [comment]
Inköpsrunda
 Motorolja
 Länspumpsslang & däcksgenomförning
 Fenderts
 Gas
 Madrass
 Mat
 Block (en-skärs, claessons)
 VHF-antenn + kabel
 Svetshjälm
 Tross
 LED-"glödlampor" till kojerna
 12 automatsäkringar 10A, 12V
 Byta olja i motorn
 Ring ny hamn
 Ta bort ruttet trä poch ersätt med plast
 Fendertrep
 Livbojshållare 90x14 + 45x14
 Skotknap
 Hyllor Höjd 110, Djup 100, bredd 50
 Hantag på durk
 Montera segel
 Måla lantärnhållarna
 El till lantärnor
 Städa & stuva
 Lämna stuff i kollektivet
 Fyll på vatten
 Fixa säkringar
 Labela säkringar och brytare
 Montera navdator
