### ISSUE TITLE
TODO - Summer

### ISSUE THREAD

**Issue by redhog** [piratpartiet/skutan#2]
# What to do when leaving the boat
* [ ] Raise matresses on their side in the beds
* [ ] Put all other fabrics / clothes / pillows in blastic sacks and tape them shut
* [ ] Put copper plate roll and metal sticks next to it somewhere under deck

# Contacts
* Contact methods for Egil & Saghar
  - +989123931571 - Saghar/Iran
  - +46760060365 - Saghar/Sweden - On telegram and Signal and whatsapp
  - +46723711268 - Egil
  - asadisaghar@gmail.com
* Harbour contact and coordinates
  * Hankø
    * https://goo.gl/maps/r3f6c3L2yyj
    * Hankø Marina AS; Vikaneveien 409, 1621 Gressvik
    * Contact: Atle
    * Email: atle@hankomarina.no
    * Phone nr: 415 35 333
    * Cutsomer nr. 31024
  * Skjebergskilen
    * [Bryggekart.pdf](https://github.com/piratpartiet/skutan/files/1798418/Bryggekart.pdf)

# What to do in emergencies
  * Sinking boat
    * Caulking (nåtning) with Linen fibers and then Sikaflex
