### ISSUE TITLE
TODO - Spring

### ISSUE THREAD

**Issue by redhog** [piratpartiet/skutan#5]
# Generic
- [ ] Change engine oil, oil filter, diesel filter and check/replace impeller
- [ ] Oil the masts
- [ ] Oil the deck
- [ ] Oil the bildge (with lots of tar)
- [ ] Caulk the deck whever needed
- [ ] Remove tarps and roofing structure
- [ ] Clean bildge (aka what is that bloody smell?!?)

# Specific to our current situation
- [ ] Move boat to summer hardbour
- [ ] Plan summer sailing
- [ ] Plan spring work weeks (sync and acquire materials)
- [ ] Plan moving the boat between harbours
