### ISSUE TITLE
TODO - Autumn

### ISSUE THREAD

**Issue by redhog** [piratpartiet/skutan#6]
* [ ] Close the two valves to the drains of the steering area (in engine compartement)
* [ ] Close the valve for the coolant water intake (under filter)
* [ ] Open coolant water filter. Slowly pour one kettle full of boiling water onto its lid and then unscrew it
* [ ] Replace coolant water in engine with glycol (10L, pour into filter while engine is running, turn engine off immediately when bucket is empty)
* [ ] Pour some glycol in
  * [ ] Drains in steering area
  * [ ] Kitchen sink
  * [ ] Toilet (pump a bit afterwards)
* [ ] Disconnect and move solar panels onto the main cabin roof
* [ ] Fix booms using boomscissors on the steering cabin roof
* [ ] Remove all loose ropes
* [ ] Remove sails
* [ ] Remove navigation computer, books and maps
* [ ] Raise booms and build roofing structure with slats of wood
* [ ] Cover boat in tarps
* [ ] Fix the heating fan with straps somewhere on the kitchen bench and connect it to a timer. Set it to lowest temperature (but still warming), and to run for 15mins every other 15mins.
* [ ] Connect bilge heating cable
* [ ] Make sure the isolation transformer is directly connected to outside power, without a power board in between
