### ISSUE TITLE
TODO - 2018

### ISSUE THREAD

**Issue by redhog** [piratpartiet/skutan#7]
- [x] Olja master, däck, insida av skrov, kölsvin

- [x] Riv och bygg om elsystemet från scratch
  - [ ] Cigguttag i kojerna
  - [ ] Byta kablar för lantärnor (Gonte & Emelie)
- [ ] Omnåtning av skrovet på relevanta ställen kan behöva ingå / göras även om kölbultarna är ok
- [ ] Hyllsystem i skåpet (Emelie & Gonte)
- [ ] Låda & durk (Emelie & Gonte)
- [ ] Handtag på durken (Emelie)
- [ ] Vålda skorstenstopp & kolla hur det ser ut innuti :) Montera tillbaka "löst" så det inte regnar in
- [ ] **Städa~**
- [ ] **Mäta saker (vanter, det kungliga skåpet, sittbrunnen)**

# Vår
- [ ] Aktervägg i styrhytt (Emelie & Gonte) (tidig vår)
- [ ] Balk på babord sida (Egil) 
- [ ] Nåta om däck under relingens knä längst fram (Egil kapar, Emelie & Gonte nåtar)
- [ ] Roder (Egil)
- [ ] Kaminmontage (Egil)
- [ ] Slangar till sittbrunnen
- [ ] Ta bort ruttet trä poch ersätt med plast
- [ ] Skotknap
- [ ] Hyllor Höjd 110, Djup 100, bredd 50
- [ ] Hantag på durk
* [ ] Fix oar holder on dingy

# Materialinköp inför våren
- [ ] Vermiculit-platta, distanser, skorstensrör för kaminmontage
- [ ] Ekplank för vägg till styrhytt (mät yta, räkna längder, vi kan inte skarva - gör en design!)
- [ ] Balk till babord sida i furu (mät längd och bredd, ta med både längsgående och tvärgående balk)
- [ ] Hitta & Beställa LED-lampor till lantärnorna E12 / E10 (Gonte)?

**Comment by redhog** [comment]
![vagg](https://user-images.githubusercontent.com/104229/37228143-dd5ec944-23df-11e8-9de9-06710d35dd68.png)
https://www.nackabyggnadsvard.se/thumb/6567/550x0/Ny-dorr.JPG
