### ISSUE TITLE
TODO: 2020 spring

### ISSUE THREAD

**Issue by redhog** [piratpartiet/skutan#8]
* [x] Close the two valves to the drains of the steering area (in engine compartement)
* [x] Close the valve for the coolant water intake (under filter)
* [x] Open coolant water filter. Slowly pour one kettle full of boiling water onto its lid and then unscrew it
* [x] Replace coolant water in engine with glycol (10L, pour into filter while engine is running, turn engine off immediately when bucket is empty)
* [x] Pour some glycol in
  * [x] Drains in steering area
  * [x] Kitchen sink
  * [x] Toilet (pump a bit afterwards)
* [x] Fix booms using boomscissors on the steering cabin roof
* [x] Remove all loose ropes
* [x] Raise booms and build roofing structure with slats of wood
* [x] Cover boat in tarps
* [x] Fix the heating fan with straps somewhere on the kitchen bench and connect it to a timer. Set it to lowest temperature (but still warming), and to run for 15mins every other 15mins.
* [x] Install dehumidifier
* [x] Ensure heating cable in bildge is connected
* [x] Install the extra 220V bildge pump
* [x] Verify functionality of all four bildge pumps and flotation switches
* [x] Make sure the isolation transformer is directly connected to outside power, without a power board in between
* [x] Check fenderts
* [x] Check mooring ropes for damage
* [ ] Call Annette when leaving so she knows that you're not on board any longer
